version: 3
tasks:
  default:
    desc: Lists all available tasks
    cmds:
      - task -l

  install-deps:
    desc: Install all dependencies
    cmds:
      - cd data-generator && pip install -r requirements.txt

  docker:up:
    desc: Starts all docker containers
    cmds:
      - docker-compose -f docker/docker-compose.yml up -d

  docker:down:
    desc: Stops all docker containers
    cmds:
      - docker-compose -f docker/docker-compose.yml down

  kafka:create-topics:
    desc: Create Kakfa topics
    cmds:
      - chmod +x scripts/kafka/create-topics.sh
      - scripts/kafka/create-topics.sh

  clickhouse:init:
    desc: Initializes ClickHouse tables
    cmds:
      - docker exec -i clickhouse-server clickhouse-client --multiquery < scripts/clickhouse/init.sql

  superset:init:
    desc: Initialize superset with admin user
    cmds:
      - docker exec -it superset superset fab create-admin
        --username admin
        --firstname Ro
        --lastname Vo
        --email ngocro208@gmail.com
        --password admin
      - docker exec -it superset superset db upgrade
      - docker exec -it superset superset init
      # SQL CONSTR: clickhouse+connect://default@clickhouse-server:8123/default

  build:
    desc: Build the application
    cmds:
      - ./gradlew clean build

  run:
    desc: Run the application
    cmds:
      - ./gradlew bootRun